---
    - name: Gather IOS Facts
      hosts: 192.168.1.33
      connection: local
      tasks:
        - name: Gather IOS Facts
          ios_facts:
            provider:
              host: 192.168.1.33
              port: 22
              username: admin
              password: cisco
              authorize: yes
              auth_pass: cisco
    
        - name: What is the IOS OS ver?
          debug:
            var: ansible_net_version
    
        - name: What is the hostname?
          debug:
            var: ansible_net_hostname
    